chore: update/fix github actions versions
dequelabs/axe-linter-action pull request #36
Opened 2024-07-25 21:23 UTC by melwynfurtado

Thanks for this Github Action!

Can we update the two actions used within to the latest version please?

Fix the version for `mikefarah/yq@v4.44.2` so it does not pull whatever goes into master.
And use latest version for `tj-actions/changed-files@v44`

Many thanks once again 🙏🏼

2024-07-29 13:48 UTC, michael-siek requested changes
Hi @melwynfurtado do you mind updating to use pinned version of the GHA deps

2024-07-29 13:48 UTC, michael-siek commented on action.yml
>      - uses: actions/checkout@v2
```suggestion
    - uses: actions/checkout@v4
```

2024-07-29 13:48 UTC, michael-siek commented on action.yml
> +    - uses: mikefarah/yq@v4.44.2
```suggestion
    - uses: mikefarah/yq@f15500b20a1c991c8729870ba60a4dc3524b6a94 # Tag=v4
```

2024-07-29 13:48 UTC, michael-siek commented on action.yml
> +      uses: tj-actions/changed-files@v44
```suggestion
      uses: tj-actions/changed-files@6b2903bdce6310cfbddd87c418f253cf29b2dec9 # Tag=v44
```

2024-07-29 18:33 UTC, melwynfurtado commented
@michael-siek thanks for looking into this. Updated to pinned versions.

2024-07-30 13:05 UTC, michael-siek approved these changes

2024-07-30 13:06 UTC, michael-siek commented
@melwynfurtado Thank you for the contribution!
- [x] reviewed for security

2024-07-30 13:07 UTC, merged

2024-07-30 20:07 UTC, melwyn-furtado commented
@michael-siek how will the versioning work? will this commit tagged as `v1` ?

2024-07-31 12:40 UTC, michael-siek commented
Hey @melwyn-furtado I will speak with the team and keep you updated.

2024-10-07 20:52 UTC, stephenmathieson commented
@michael-siek what did the team say regarding versioning?